import Footer from "@/components/global/Footer";
import Navbar from "@/components/global/Navbar";
import store from "@/context/store";
import { authUser } from "@/functions/user.query";
import "@/styles/globals.css";
import { authenticated } from "@/types/auth.type";
import type { AppProps } from "next/app";
import Head from "next/head";
import { useEffect, useState } from "react";
import { Provider } from "react-redux";

function App({ Component, pageProps }: AppProps) {
  useEffect(()=>{
    const token=localStorage.getItem('tkn') 
    token&&    
    token&&authUser()
  },[])  
  return (
    <>
      <Head>
        <title>CantaJuega Conmigo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`bg-light w-full min-h-screen`}>
        <Provider store={store}>
          <Navbar />
          <Component {...pageProps} />
        </Provider>
      <Footer />
      </main>
    </>
  );
}

export default App;
